services:
  - type: web
    name: annonces-immobilieres-abidjan
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        value: annonces.db
    healthCheckPath: /health

  # Service worker pour le scraping automatique
  - type: worker
    name: annonce-scraper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scraper.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: DATABASE_URL
        value: annonces.db