services:
  - type: web
    name: annonces-immobilieres-abidjan
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

  - type: worker
    name: annonce-scraper
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scraper.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9